apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-pokemon
  labels:
    apps: frontend-pokemon
spec:
  selector:
    matchLabels:
      app: frontend-pokemon
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-pokemon
    spec:
      containers:
        - name: frontend-pokemon
          image: registry.gitlab.com/ryandf1998/frontend-pokemon
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry.gitlab.com
